Search.appendIndex(
    [
                {
            "fqsen": "\\Pock\\Client",
            "name": "Client",
            "summary": "Class\u0020Client",
            "url": "classes/Pock-Client.html"
        },                {
            "fqsen": "\\Pock\\Client\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Client\u0020constructor.",
            "url": "classes/Pock-Client.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Client\u003A\u003AdoSendRequest\u0028\u0029",
            "name": "doSendRequest",
            "summary": "",
            "url": "classes/Pock-Client.html#method_doSendRequest"
        },                {
            "fqsen": "\\Pock\\Client\u003A\u003AsendRequest\u0028\u0029",
            "name": "sendRequest",
            "summary": "",
            "url": "classes/Pock-Client.html#method_sendRequest"
        },                {
            "fqsen": "\\Pock\\Client\u003A\u003AsendAsyncRequest\u0028\u0029",
            "name": "sendAsyncRequest",
            "summary": "",
            "url": "classes/Pock-Client.html#method_sendAsyncRequest"
        },                {
            "fqsen": "\\Pock\\Comparator\\ComparatorInterface",
            "name": "ComparatorInterface",
            "summary": "Interface\u0020ComparatorInterface",
            "url": "classes/Pock-Comparator-ComparatorInterface.html"
        },                {
            "fqsen": "\\Pock\\Comparator\\ComparatorInterface\u003A\u003Acompare\u0028\u0029",
            "name": "compare",
            "summary": "Compare\u0020two\u0020values.",
            "url": "classes/Pock-Comparator-ComparatorInterface.html#method_compare"
        },                {
            "fqsen": "\\Pock\\Comparator\\ComparatorLocator",
            "name": "ComparatorLocator",
            "summary": "Class\u0020ComparatorLocator",
            "url": "classes/Pock-Comparator-ComparatorLocator.html"
        },                {
            "fqsen": "\\Pock\\Comparator\\ComparatorLocator\u003A\u003Aget\u0028\u0029",
            "name": "get",
            "summary": "Returns\u0020comparator.",
            "url": "classes/Pock-Comparator-ComparatorLocator.html#method_get"
        },                {
            "fqsen": "\\Pock\\Comparator\\LtrScalarArrayComparator",
            "name": "LtrScalarArrayComparator",
            "summary": "Class\u0020LtrScalarArrayComparator",
            "url": "classes/Pock-Comparator-LtrScalarArrayComparator.html"
        },                {
            "fqsen": "\\Pock\\Comparator\\LtrScalarArrayComparator\u003A\u003Acompare\u0028\u0029",
            "name": "compare",
            "summary": "Compare\u0020two\u0020values.",
            "url": "classes/Pock-Comparator-LtrScalarArrayComparator.html#method_compare"
        },                {
            "fqsen": "\\Pock\\Comparator\\RecursiveArrayComparator",
            "name": "RecursiveArrayComparator",
            "summary": "Class\u0020RecursiveArrayComparator",
            "url": "classes/Pock-Comparator-RecursiveArrayComparator.html"
        },                {
            "fqsen": "\\Pock\\Comparator\\RecursiveArrayComparator\u003A\u003Acompare\u0028\u0029",
            "name": "compare",
            "summary": "Compare\u0020two\u0020values.",
            "url": "classes/Pock-Comparator-RecursiveArrayComparator.html#method_compare"
        },                {
            "fqsen": "\\Pock\\Comparator\\RecursiveLtrArrayComparator",
            "name": "RecursiveLtrArrayComparator",
            "summary": "Class\u0020RecursiveLtrArrayComparator",
            "url": "classes/Pock-Comparator-RecursiveLtrArrayComparator.html"
        },                {
            "fqsen": "\\Pock\\Comparator\\RecursiveLtrArrayComparator\u003A\u003Acompare\u0028\u0029",
            "name": "compare",
            "summary": "Compare\u0020two\u0020values.",
            "url": "classes/Pock-Comparator-RecursiveLtrArrayComparator.html#method_compare"
        },                {
            "fqsen": "\\Pock\\Comparator\\ScalarFlatArrayComparator",
            "name": "ScalarFlatArrayComparator",
            "summary": "Class\u0020ScalarFlatArrayComparator",
            "url": "classes/Pock-Comparator-ScalarFlatArrayComparator.html"
        },                {
            "fqsen": "\\Pock\\Comparator\\ScalarFlatArrayComparator\u003A\u003Acompare\u0028\u0029",
            "name": "compare",
            "summary": "Compare\u0020two\u0020values.",
            "url": "classes/Pock-Comparator-ScalarFlatArrayComparator.html#method_compare"
        },                {
            "fqsen": "\\Pock\\Creator\\AbstractJmsSerializerCreator",
            "name": "AbstractJmsSerializerCreator",
            "summary": "Class\u0020AbstractJmsSerializerCreator",
            "url": "classes/Pock-Creator-AbstractJmsSerializerCreator.html"
        },                {
            "fqsen": "\\Pock\\Creator\\AbstractJmsSerializerCreator\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Instantiates\u0020serializer\u0020and\u0020returns\u0020it.\u0020Returns\u0020null\u0020if\u0020serializer\u0020cannot\u0020be\u0020located.",
            "url": "classes/Pock-Creator-AbstractJmsSerializerCreator.html#method_create"
        },                {
            "fqsen": "\\Pock\\Creator\\AbstractSymfonySerializerCreator",
            "name": "AbstractSymfonySerializerCreator",
            "summary": "Class\u0020AbstractSymfonySerializerCreator",
            "url": "classes/Pock-Creator-AbstractSymfonySerializerCreator.html"
        },                {
            "fqsen": "\\Pock\\Creator\\AbstractSymfonySerializerCreator\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Instantiates\u0020serializer\u0020and\u0020returns\u0020it.\u0020Returns\u0020null\u0020if\u0020serializer\u0020cannot\u0020be\u0020located.",
            "url": "classes/Pock-Creator-AbstractSymfonySerializerCreator.html#method_create"
        },                {
            "fqsen": "\\Pock\\Creator\\JmsJsonSerializerCreator",
            "name": "JmsJsonSerializerCreator",
            "summary": "Class\u0020JmsJsonSerializerCreator",
            "url": "classes/Pock-Creator-JmsJsonSerializerCreator.html"
        },                {
            "fqsen": "\\Pock\\Creator\\JmsXmlSerializerCreator",
            "name": "JmsXmlSerializerCreator",
            "summary": "Class\u0020JmsXmlSerializerCreator",
            "url": "classes/Pock-Creator-JmsXmlSerializerCreator.html"
        },                {
            "fqsen": "\\Pock\\Creator\\SerializerCreatorInterface",
            "name": "SerializerCreatorInterface",
            "summary": "Interface\u0020SerializerCreatorInterface",
            "url": "classes/Pock-Creator-SerializerCreatorInterface.html"
        },                {
            "fqsen": "\\Pock\\Creator\\SerializerCreatorInterface\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Instantiates\u0020serializer\u0020and\u0020returns\u0020it.\u0020Returns\u0020null\u0020if\u0020serializer\u0020cannot\u0020be\u0020located.",
            "url": "classes/Pock-Creator-SerializerCreatorInterface.html#method_create"
        },                {
            "fqsen": "\\Pock\\Creator\\SymfonyJsonSerializerCreator",
            "name": "SymfonyJsonSerializerCreator",
            "summary": "Class\u0020SymfonyJsonSerializerCreator",
            "url": "classes/Pock-Creator-SymfonyJsonSerializerCreator.html"
        },                {
            "fqsen": "\\Pock\\Creator\\SymfonyXmlSerializerCreator",
            "name": "SymfonyXmlSerializerCreator",
            "summary": "Class\u0020SymfonyXmlSerializerCreator",
            "url": "classes/Pock-Creator-SymfonyXmlSerializerCreator.html"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod",
            "name": "RequestMethod",
            "summary": "Class\u0020RequestMethod",
            "url": "classes/Pock-Enum-RequestMethod.html"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod\u003A\u003AGET",
            "name": "GET",
            "summary": "",
            "url": "classes/Pock-Enum-RequestMethod.html#constant_GET"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod\u003A\u003AHEAD",
            "name": "HEAD",
            "summary": "",
            "url": "classes/Pock-Enum-RequestMethod.html#constant_HEAD"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod\u003A\u003APOST",
            "name": "POST",
            "summary": "",
            "url": "classes/Pock-Enum-RequestMethod.html#constant_POST"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod\u003A\u003APUT",
            "name": "PUT",
            "summary": "",
            "url": "classes/Pock-Enum-RequestMethod.html#constant_PUT"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod\u003A\u003APATCH",
            "name": "PATCH",
            "summary": "",
            "url": "classes/Pock-Enum-RequestMethod.html#constant_PATCH"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod\u003A\u003ADELETE",
            "name": "DELETE",
            "summary": "",
            "url": "classes/Pock-Enum-RequestMethod.html#constant_DELETE"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod\u003A\u003ACONNECT",
            "name": "CONNECT",
            "summary": "",
            "url": "classes/Pock-Enum-RequestMethod.html#constant_CONNECT"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod\u003A\u003AOPTIONS",
            "name": "OPTIONS",
            "summary": "",
            "url": "classes/Pock-Enum-RequestMethod.html#constant_OPTIONS"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestMethod\u003A\u003ATRACE",
            "name": "TRACE",
            "summary": "",
            "url": "classes/Pock-Enum-RequestMethod.html#constant_TRACE"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestScheme",
            "name": "RequestScheme",
            "summary": "Class\u0020RequestScheme",
            "url": "classes/Pock-Enum-RequestScheme.html"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestScheme\u003A\u003AHTTP",
            "name": "HTTP",
            "summary": "",
            "url": "classes/Pock-Enum-RequestScheme.html#constant_HTTP"
        },                {
            "fqsen": "\\Pock\\Enum\\RequestScheme\u003A\u003AHTTPS",
            "name": "HTTPS",
            "summary": "",
            "url": "classes/Pock-Enum-RequestScheme.html#constant_HTTPS"
        },                {
            "fqsen": "\\Pock\\Exception\\AbstractRequestAwareException",
            "name": "AbstractRequestAwareException",
            "summary": "Class\u0020AbstractRequestAwareException",
            "url": "classes/Pock-Exception-AbstractRequestAwareException.html"
        },                {
            "fqsen": "\\Pock\\Exception\\AbstractRequestAwareException\u003A\u003AsetRequest\u0028\u0029",
            "name": "setRequest",
            "summary": "",
            "url": "classes/Pock-Exception-AbstractRequestAwareException.html#method_setRequest"
        },                {
            "fqsen": "\\Pock\\Exception\\AbstractRequestAwareException\u003A\u003AgetRequest\u0028\u0029",
            "name": "getRequest",
            "summary": "",
            "url": "classes/Pock-Exception-AbstractRequestAwareException.html#method_getRequest"
        },                {
            "fqsen": "\\Pock\\Exception\\IncompleteMockException",
            "name": "IncompleteMockException",
            "summary": "Class\u0020IncompleteMockException",
            "url": "classes/Pock-Exception-IncompleteMockException.html"
        },                {
            "fqsen": "\\Pock\\Exception\\IncompleteMockException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "AbstractMockException\u0020constructor.",
            "url": "classes/Pock-Exception-IncompleteMockException.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Exception\\IncompleteMockException\u003A\u003AgetMock\u0028\u0029",
            "name": "getMock",
            "summary": "",
            "url": "classes/Pock-Exception-IncompleteMockException.html#method_getMock"
        },                {
            "fqsen": "\\Pock\\Exception\\JsonException",
            "name": "JsonException",
            "summary": "Class\u0020JsonException",
            "url": "classes/Pock-Exception-JsonException.html"
        },                {
            "fqsen": "\\Pock\\Exception\\PockClientException",
            "name": "PockClientException",
            "summary": "Class\u0020PockClientException",
            "url": "classes/Pock-Exception-PockClientException.html"
        },                {
            "fqsen": "\\Pock\\Exception\\PockNetworkException",
            "name": "PockNetworkException",
            "summary": "Class\u0020PockNetworkException",
            "url": "classes/Pock-Exception-PockNetworkException.html"
        },                {
            "fqsen": "\\Pock\\Exception\\PockRequestException",
            "name": "PockRequestException",
            "summary": "Class\u0020PockRequestException",
            "url": "classes/Pock-Exception-PockRequestException.html"
        },                {
            "fqsen": "\\Pock\\Exception\\UnsupportedRequestException",
            "name": "UnsupportedRequestException",
            "summary": "Class\u0020UnsupportedRequestException",
            "url": "classes/Pock-Exception-UnsupportedRequestException.html"
        },                {
            "fqsen": "\\Pock\\Exception\\UnsupportedRequestException\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pock-Exception-UnsupportedRequestException.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Exception\\XmlException",
            "name": "XmlException",
            "summary": "Class\u0020XmlException",
            "url": "classes/Pock-Exception-XmlException.html"
        },                {
            "fqsen": "\\Pock\\Factory\\AbstractSerializerFactory",
            "name": "AbstractSerializerFactory",
            "summary": "Class\u0020AbstractSerializerFactory",
            "url": "classes/Pock-Factory-AbstractSerializerFactory.html"
        },                {
            "fqsen": "\\Pock\\Factory\\AbstractSerializerFactory\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "Instantiate\u0020first\u0020available\u0020serializer.",
            "url": "classes/Pock-Factory-AbstractSerializerFactory.html#method_create"
        },                {
            "fqsen": "\\Pock\\Factory\\CallbackReplyFactory",
            "name": "CallbackReplyFactory",
            "summary": "Class\u0020CallbackReplyFactory",
            "url": "classes/Pock-Factory-CallbackReplyFactory.html"
        },                {
            "fqsen": "\\Pock\\Factory\\CallbackReplyFactory\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "CallbackReplyFactory\u0020constructor.",
            "url": "classes/Pock-Factory-CallbackReplyFactory.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Factory\\CallbackReplyFactory\u003A\u003AcreateReply\u0028\u0029",
            "name": "createReply",
            "summary": "Reply\u0020to\u0020the\u0020specified\u0020request.",
            "url": "classes/Pock-Factory-CallbackReplyFactory.html#method_createReply"
        },                {
            "fqsen": "\\Pock\\Factory\\JsonSerializerFactory",
            "name": "JsonSerializerFactory",
            "summary": "Class\u0020JsonSerializerFactory",
            "url": "classes/Pock-Factory-JsonSerializerFactory.html"
        },                {
            "fqsen": "\\Pock\\Factory\\JsonSerializerFactory\u003A\u003AsetSerializer\u0028\u0029",
            "name": "setSerializer",
            "summary": "",
            "url": "classes/Pock-Factory-JsonSerializerFactory.html#method_setSerializer"
        },                {
            "fqsen": "\\Pock\\Factory\\ReplyFactoryInterface",
            "name": "ReplyFactoryInterface",
            "summary": "Interface\u0020ReplyFactoryInterface",
            "url": "classes/Pock-Factory-ReplyFactoryInterface.html"
        },                {
            "fqsen": "\\Pock\\Factory\\ReplyFactoryInterface\u003A\u003AcreateReply\u0028\u0029",
            "name": "createReply",
            "summary": "Reply\u0020to\u0020the\u0020specified\u0020request.",
            "url": "classes/Pock-Factory-ReplyFactoryInterface.html#method_createReply"
        },                {
            "fqsen": "\\Pock\\Factory\\XmlSerializerFactory",
            "name": "XmlSerializerFactory",
            "summary": "Class\u0020XmlSerializerFactory",
            "url": "classes/Pock-Factory-XmlSerializerFactory.html"
        },                {
            "fqsen": "\\Pock\\Factory\\XmlSerializerFactory\u003A\u003AsetSerializer\u0028\u0029",
            "name": "setSerializer",
            "summary": "",
            "url": "classes/Pock-Factory-XmlSerializerFactory.html#method_setSerializer"
        },                {
            "fqsen": "\\Pock\\Matchers\\AbstractRegExpMatcher",
            "name": "AbstractRegExpMatcher",
            "summary": "Class\u0020AbstractRegExpMatcher",
            "url": "classes/Pock-Matchers-AbstractRegExpMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\AbstractRegExpMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/Pock-Matchers-AbstractRegExpMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\AbstractSerializedBodyMatcher",
            "name": "AbstractSerializedBodyMatcher",
            "summary": "Class\u0020AbstractSerializedBodyMatcher",
            "url": "classes/Pock-Matchers-AbstractSerializedBodyMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\AbstractSerializedBodyMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "AbstractSerializedBodyMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-AbstractSerializedBodyMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\AbstractSerializedBodyMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-AbstractSerializedBodyMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\AnyRequestMatcher",
            "name": "AnyRequestMatcher",
            "summary": "Class\u0020AnyRequestMatcher",
            "url": "classes/Pock-Matchers-AnyRequestMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\AnyRequestMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-AnyRequestMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\BodyMatcher",
            "name": "BodyMatcher",
            "summary": "Class\u0020BodyMatcher",
            "url": "classes/Pock-Matchers-BodyMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\BodyMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "BodyMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-BodyMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\BodyMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-BodyMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\CallbackRequestMatcher",
            "name": "CallbackRequestMatcher",
            "summary": "Class\u0020CallbackRequestMatcher",
            "url": "classes/Pock-Matchers-CallbackRequestMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\CallbackRequestMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "CallbackRequestMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-CallbackRequestMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\CallbackRequestMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-CallbackRequestMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\ExactFormDataMatcher",
            "name": "ExactFormDataMatcher",
            "summary": "Class\u0020ExactFormDataMatcher",
            "url": "classes/Pock-Matchers-ExactFormDataMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\ExactFormDataMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-ExactFormDataMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\ExactHeaderMatcher",
            "name": "ExactHeaderMatcher",
            "summary": "Class\u0020ExactHeaderMatcher",
            "url": "classes/Pock-Matchers-ExactHeaderMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\ExactHeaderMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-ExactHeaderMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\ExactHeadersMatcher",
            "name": "ExactHeadersMatcher",
            "summary": "Class\u0020ExactHeadersMatcher",
            "url": "classes/Pock-Matchers-ExactHeadersMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\ExactHeadersMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-ExactHeadersMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\ExactQueryMatcher",
            "name": "ExactQueryMatcher",
            "summary": "Class\u0020ExactQueryMatcher",
            "url": "classes/Pock-Matchers-ExactQueryMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\ExactQueryMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-ExactQueryMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\FormDataMatcher",
            "name": "FormDataMatcher",
            "summary": "Class\u0020FormDataMatcher",
            "url": "classes/Pock-Matchers-FormDataMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\FormDataMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-FormDataMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeaderLineMatcher",
            "name": "HeaderLineMatcher",
            "summary": "Class\u0020HeaderLineMatcher",
            "url": "classes/Pock-Matchers-HeaderLineMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeaderLineMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HeaderLineMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-HeaderLineMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeaderLineMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-HeaderLineMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeaderLineRegexpMatcher",
            "name": "HeaderLineRegexpMatcher",
            "summary": "Class\u0020HeaderLineRegexpMatcher",
            "url": "classes/Pock-Matchers-HeaderLineRegexpMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeaderLineRegexpMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HeaderLineRegexpMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-HeaderLineRegexpMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeaderLineRegexpMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-HeaderLineRegexpMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeaderMatcher",
            "name": "HeaderMatcher",
            "summary": "Class\u0020HeaderMatcher",
            "url": "classes/Pock-Matchers-HeaderMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeaderMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HeaderMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-HeaderMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeaderMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-HeaderMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeadersMatcher",
            "name": "HeadersMatcher",
            "summary": "Class\u0020HeadersMatcher",
            "url": "classes/Pock-Matchers-HeadersMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeadersMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HeadersMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-HeadersMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\HeadersMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-HeadersMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\HostMatcher",
            "name": "HostMatcher",
            "summary": "Class\u0020HostMatcher",
            "url": "classes/Pock-Matchers-HostMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\HostMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HostMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-HostMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\HostMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-HostMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\JsonBodyMatcher",
            "name": "JsonBodyMatcher",
            "summary": "Class\u0020JsonBodyMatcher",
            "url": "classes/Pock-Matchers-JsonBodyMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\MethodMatcher",
            "name": "MethodMatcher",
            "summary": "Class\u0020MethodMatcher",
            "url": "classes/Pock-Matchers-MethodMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\MethodMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MethodMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-MethodMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\MethodMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-MethodMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\MultipartFormDataMatcher",
            "name": "MultipartFormDataMatcher",
            "summary": "Class\u0020MultipartFormDataMatcher",
            "url": "classes/Pock-Matchers-MultipartFormDataMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\MultipartFormDataMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MultipartFormDataMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-MultipartFormDataMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\MultipartFormDataMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-MultipartFormDataMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\MultipleMatcher",
            "name": "MultipleMatcher",
            "summary": "Class\u0020MultipleMatcher",
            "url": "classes/Pock-Matchers-MultipleMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\MultipleMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "MultipleMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-MultipleMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\MultipleMatcher\u003A\u003AaddMatcher\u0028\u0029",
            "name": "addMatcher",
            "summary": "",
            "url": "classes/Pock-Matchers-MultipleMatcher.html#method_addMatcher"
        },                {
            "fqsen": "\\Pock\\Matchers\\MultipleMatcher\u003A\u003Acount\u0028\u0029",
            "name": "count",
            "summary": "",
            "url": "classes/Pock-Matchers-MultipleMatcher.html#method_count"
        },                {
            "fqsen": "\\Pock\\Matchers\\MultipleMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-MultipleMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\MultipleMatcher\u003A\u003A\u0024matchers",
            "name": "matchers",
            "summary": "",
            "url": "classes/Pock-Matchers-MultipleMatcher.html#property_matchers"
        },                {
            "fqsen": "\\Pock\\Matchers\\PathMatcher",
            "name": "PathMatcher",
            "summary": "Class\u0020PathMatcher",
            "url": "classes/Pock-Matchers-PathMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\PathMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "PathMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-PathMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\PathMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-PathMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\PortMatcher",
            "name": "PortMatcher",
            "summary": "Class\u0020PortMatcher",
            "url": "classes/Pock-Matchers-PortMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\PortMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "PortMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-PortMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\PortMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-PortMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\QueryMatcher",
            "name": "QueryMatcher",
            "summary": "Class\u0020QueryMatcher",
            "url": "classes/Pock-Matchers-QueryMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\QueryMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "QueryMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-QueryMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\QueryMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-QueryMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\RegExpBodyMatcher",
            "name": "RegExpBodyMatcher",
            "summary": "Class\u0020RegExpBodyMatcher",
            "url": "classes/Pock-Matchers-RegExpBodyMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\RegExpBodyMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "",
            "url": "classes/Pock-Matchers-RegExpBodyMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\RegExpPathMatcher",
            "name": "RegExpPathMatcher",
            "summary": "Class\u0020RegExpPathMatcher",
            "url": "classes/Pock-Matchers-RegExpPathMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\RegExpPathMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "",
            "url": "classes/Pock-Matchers-RegExpPathMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\RegExpQueryMatcher",
            "name": "RegExpQueryMatcher",
            "summary": "Class\u0020RegExpQueryMatcher",
            "url": "classes/Pock-Matchers-RegExpQueryMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\RegExpQueryMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "",
            "url": "classes/Pock-Matchers-RegExpQueryMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\RegExpUriMatcher",
            "name": "RegExpUriMatcher",
            "summary": "Class\u0020RegExpUriMatcher",
            "url": "classes/Pock-Matchers-RegExpUriMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\RegExpUriMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "",
            "url": "classes/Pock-Matchers-RegExpUriMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\RequestMatcherInterface",
            "name": "RequestMatcherInterface",
            "summary": "Interface\u0020RequestMatcherInterface",
            "url": "classes/Pock-Matchers-RequestMatcherInterface.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\RequestMatcherInterface\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-RequestMatcherInterface.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\SchemeMatcher",
            "name": "SchemeMatcher",
            "summary": "Class\u0020SchemeMatcher",
            "url": "classes/Pock-Matchers-SchemeMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\SchemeMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "SchemeMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-SchemeMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\SchemeMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-SchemeMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\UriMatcher",
            "name": "UriMatcher",
            "summary": "Class\u0020UriMatcher",
            "url": "classes/Pock-Matchers-UriMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\UriMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "UriMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-UriMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\UriMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-UriMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\XmlBodyMatcher",
            "name": "XmlBodyMatcher",
            "summary": "Class\u0020XmlBodyMatcher",
            "url": "classes/Pock-Matchers-XmlBodyMatcher.html"
        },                {
            "fqsen": "\\Pock\\Matchers\\XmlBodyMatcher\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "XmlBodyMatcher\u0020constructor.",
            "url": "classes/Pock-Matchers-XmlBodyMatcher.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Matchers\\XmlBodyMatcher\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020request\u0020is\u0020matched\u0020by\u0020this\u0020matcher.",
            "url": "classes/Pock-Matchers-XmlBodyMatcher.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Matchers\\XmlBodyMatcher\u003A\u003A\u0024forceTextComparison",
            "name": "forceTextComparison",
            "summary": "",
            "url": "classes/Pock-Matchers-XmlBodyMatcher.html#property_forceTextComparison"
        },                {
            "fqsen": "\\Pock\\Mock",
            "name": "Mock",
            "summary": "Class\u0020Mock",
            "url": "classes/Pock-Mock.html"
        },                {
            "fqsen": "\\Pock\\Mock\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Mock\u0020constructor.",
            "url": "classes/Pock-Mock.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Mock\u003A\u003AregisterHit\u0028\u0029",
            "name": "registerHit",
            "summary": "Registers\u0020a\u0020hit\u0020to\u0020the\u0020mock.",
            "url": "classes/Pock-Mock.html#method_registerHit"
        },                {
            "fqsen": "\\Pock\\Mock\u003A\u003Aavailable\u0028\u0029",
            "name": "available",
            "summary": "Returns\u0020true\u0020if\u0020mock\u0020is\u0020still\u0020can\u0020be\u0020used.",
            "url": "classes/Pock-Mock.html#method_available"
        },                {
            "fqsen": "\\Pock\\Mock\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020underlying\u0020matcher\u0020has\u0020matched\u0020provided\u0020request.",
            "url": "classes/Pock-Mock.html#method_matches"
        },                {
            "fqsen": "\\Pock\\Mock\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "Returns\u0020response\u0020which\u0020should\u0020be\u0020used\u0020as\u0020mock\u0020data.",
            "url": "classes/Pock-Mock.html#method_getResponse"
        },                {
            "fqsen": "\\Pock\\Mock\u003A\u003AgetReplyFactory\u0028\u0029",
            "name": "getReplyFactory",
            "summary": "Returns\u0020reply\u0020factory\u0020which\u0020should\u0020be\u0020used\u0020to\u0020form\u0020the\u0020mocked\u0020response.",
            "url": "classes/Pock-Mock.html#method_getReplyFactory"
        },                {
            "fqsen": "\\Pock\\Mock\u003A\u003AgetThrowable\u0028\u0029",
            "name": "getThrowable",
            "summary": "Returns\u0020the\u0020throwable\u0020which\u0020will\u0020be\u0020thrown\u0020as\u0020mock\u0020data.",
            "url": "classes/Pock-Mock.html#method_getThrowable"
        },                {
            "fqsen": "\\Pock\\MockInterface",
            "name": "MockInterface",
            "summary": "Interface\u0020MockInterface",
            "url": "classes/Pock-MockInterface.html"
        },                {
            "fqsen": "\\Pock\\MockInterface\u003A\u003AregisterHit\u0028\u0029",
            "name": "registerHit",
            "summary": "Registers\u0020a\u0020hit\u0020to\u0020the\u0020mock.",
            "url": "classes/Pock-MockInterface.html#method_registerHit"
        },                {
            "fqsen": "\\Pock\\MockInterface\u003A\u003Aavailable\u0028\u0029",
            "name": "available",
            "summary": "Returns\u0020true\u0020if\u0020mock\u0020is\u0020still\u0020can\u0020be\u0020used.",
            "url": "classes/Pock-MockInterface.html#method_available"
        },                {
            "fqsen": "\\Pock\\MockInterface\u003A\u003Amatches\u0028\u0029",
            "name": "matches",
            "summary": "Returns\u0020true\u0020if\u0020underlying\u0020matcher\u0020has\u0020matched\u0020provided\u0020request.",
            "url": "classes/Pock-MockInterface.html#method_matches"
        },                {
            "fqsen": "\\Pock\\MockInterface\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "Returns\u0020response\u0020which\u0020should\u0020be\u0020used\u0020as\u0020mock\u0020data.",
            "url": "classes/Pock-MockInterface.html#method_getResponse"
        },                {
            "fqsen": "\\Pock\\MockInterface\u003A\u003AgetReplyFactory\u0028\u0029",
            "name": "getReplyFactory",
            "summary": "Returns\u0020reply\u0020factory\u0020which\u0020should\u0020be\u0020used\u0020to\u0020form\u0020the\u0020mocked\u0020response.",
            "url": "classes/Pock-MockInterface.html#method_getReplyFactory"
        },                {
            "fqsen": "\\Pock\\MockInterface\u003A\u003AgetThrowable\u0028\u0029",
            "name": "getThrowable",
            "summary": "Returns\u0020the\u0020throwable\u0020which\u0020will\u0020be\u0020thrown\u0020as\u0020mock\u0020data.",
            "url": "classes/Pock-MockInterface.html#method_getThrowable"
        },                {
            "fqsen": "\\Pock\\PockBuilder",
            "name": "PockBuilder",
            "summary": "Class\u0020PockBuilder",
            "url": "classes/Pock-PockBuilder.html"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "PockBuilder\u0020constructor.",
            "url": "classes/Pock-PockBuilder.html#method___construct"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchMethod\u0028\u0029",
            "name": "matchMethod",
            "summary": "Match\u0020request\u0020by\u0020its\u0020method.",
            "url": "classes/Pock-PockBuilder.html#method_matchMethod"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchScheme\u0028\u0029",
            "name": "matchScheme",
            "summary": "Match\u0020request\u0020by\u0020its\u0020scheme.",
            "url": "classes/Pock-PockBuilder.html#method_matchScheme"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchHost\u0028\u0029",
            "name": "matchHost",
            "summary": "Matches\u0020request\u0020by\u0020hostname.",
            "url": "classes/Pock-PockBuilder.html#method_matchHost"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchPort\u0028\u0029",
            "name": "matchPort",
            "summary": "Matches\u0020request\u0020by\u0020the\u0020port.",
            "url": "classes/Pock-PockBuilder.html#method_matchPort"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchOrigin\u0028\u0029",
            "name": "matchOrigin",
            "summary": "Matches\u0020request\u0020by\u0020origin.",
            "url": "classes/Pock-PockBuilder.html#method_matchOrigin"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchUri\u0028\u0029",
            "name": "matchUri",
            "summary": "Matches\u0020request\u0020by\u0020the\u0020whole\u0020URI.",
            "url": "classes/Pock-PockBuilder.html#method_matchUri"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchUriRegExp\u0028\u0029",
            "name": "matchUriRegExp",
            "summary": "Matches\u0020request\u0020by\u0020the\u0020whole\u0020URI\u0020using\u0020regular\u0020expression.",
            "url": "classes/Pock-PockBuilder.html#method_matchUriRegExp"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchHeader\u0028\u0029",
            "name": "matchHeader",
            "summary": "Matches\u0020request\u0020by\u0020header\u0020value\u0020or\u0020several\u0020values.\u0020Header\u0020can\u0020have\u0020other\u0020values\u0020which\u0020are\u0020not\u0020specified\u0020here.",
            "url": "classes/Pock-PockBuilder.html#method_matchHeader"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchHeaders\u0028\u0029",
            "name": "matchHeaders",
            "summary": "Matches\u0020request\u0020by\u0020headers\u0020values\u0020or\u0020several\u0020values.\u0020Headers\u0020can\u0020have\u0020other\u0020values\u0020which\u0020are\u0020not\u0020specified\u0020here.",
            "url": "classes/Pock-PockBuilder.html#method_matchHeaders"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchExactHeader\u0028\u0029",
            "name": "matchExactHeader",
            "summary": "Matches\u0020request\u0020by\u0020the\u0020exact\u0020header\u0020pattern\u0020or\u0020values.",
            "url": "classes/Pock-PockBuilder.html#method_matchExactHeader"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchExactHeaders\u0028\u0029",
            "name": "matchExactHeaders",
            "summary": "Matches\u0020request\u0020by\u0020headers\u0020values\u0020or\u0020several\u0020values.",
            "url": "classes/Pock-PockBuilder.html#method_matchExactHeaders"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchHeaderLine\u0028\u0029",
            "name": "matchHeaderLine",
            "summary": "Matches\u0020request\u0020by\u0020the\u0020unparsed\u0020header\u0020line.",
            "url": "classes/Pock-PockBuilder.html#method_matchHeaderLine"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchHeaderLineRegexp\u0028\u0029",
            "name": "matchHeaderLineRegexp",
            "summary": "Matches\u0020request\u0020by\u0020the\u0020unparsed\u0020header\u0020line\u0020using\u0020provided\u0020regular\u0020expression.",
            "url": "classes/Pock-PockBuilder.html#method_matchHeaderLineRegexp"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchPath\u0028\u0029",
            "name": "matchPath",
            "summary": "Match\u0020request\u0020by\u0020its\u0020path.\u0020Path\u0020with\u0020and\u0020without\u0020slash\u0020at\u0020the\u0020start\u0020will\u0020be\u0020treated\u0020as\u0020the\u0020same\u0020path.",
            "url": "classes/Pock-PockBuilder.html#method_matchPath"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchPathRegExp\u0028\u0029",
            "name": "matchPathRegExp",
            "summary": "Match\u0020request\u0020by\u0020its\u0020path\u0020using\u0020regular\u0020expression.\u0020This\u0020matcher\u0020doesn\u0027t\u0020care\u0020about\u0020prefix\u0020slash\nsince\u0020it\u0027s\u0020pretty\u0020easy\u0020to\u0020do\u0020it\u0020using\u0020regular\u0020expression.",
            "url": "classes/Pock-PockBuilder.html#method_matchPathRegExp"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchQuery\u0028\u0029",
            "name": "matchQuery",
            "summary": "Match\u0020request\u0020by\u0020its\u0020query.\u0020Request\u0020can\u0020contain\u0020other\u0020query\u0020variables.",
            "url": "classes/Pock-PockBuilder.html#method_matchQuery"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchQueryRegExp\u0028\u0029",
            "name": "matchQueryRegExp",
            "summary": "Match\u0020request\u0020by\u0020its\u0020query\u0020using\u0020regular\u0020expression.",
            "url": "classes/Pock-PockBuilder.html#method_matchQueryRegExp"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchExactQuery\u0028\u0029",
            "name": "matchExactQuery",
            "summary": "Match\u0020request\u0020by\u0020its\u0020query.\u0020Additional\u0020query\u0020parameters\u0020aren\u0027t\u0020allowed.",
            "url": "classes/Pock-PockBuilder.html#method_matchExactQuery"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchFormData\u0028\u0029",
            "name": "matchFormData",
            "summary": "Match\u0020request\u0020with\u0020form\u002Ddata.",
            "url": "classes/Pock-PockBuilder.html#method_matchFormData"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchExactFormData\u0028\u0029",
            "name": "matchExactFormData",
            "summary": "Match\u0020request\u0020with\u0020form\u002Ddata.\u0020Additional\u0020fields\u0020aren\u0027t\u0020allowed.",
            "url": "classes/Pock-PockBuilder.html#method_matchExactFormData"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchMultipartFormData\u0028\u0029",
            "name": "matchMultipartFormData",
            "summary": "Match\u0020request\u0020multipart\u0020form\u0020data.\u0020Will\u0020not\u0020match\u0020the\u0020request\u0020if\u0020body\u0020is\u0020not\u0020multipart.",
            "url": "classes/Pock-PockBuilder.html#method_matchMultipartFormData"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchBody\u0028\u0029",
            "name": "matchBody",
            "summary": "Match\u0020entire\u0020request\u0020body.",
            "url": "classes/Pock-PockBuilder.html#method_matchBody"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchBodyRegExp\u0028\u0029",
            "name": "matchBodyRegExp",
            "summary": "Match\u0020entire\u0020request\u0020body\u0020using\u0020provided\u0020regular\u0020expression.",
            "url": "classes/Pock-PockBuilder.html#method_matchBodyRegExp"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchJsonBody\u0028\u0029",
            "name": "matchJsonBody",
            "summary": "Match\u0020JSON\u0020request\u0020body.",
            "url": "classes/Pock-PockBuilder.html#method_matchJsonBody"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchSerializedJsonBody\u0028\u0029",
            "name": "matchSerializedJsonBody",
            "summary": "Match\u0020JSON\u0020request\u0020body\u0020against\u0020JSON\u0020string\u0020or\u0020array\u0020with\u0020data.",
            "url": "classes/Pock-PockBuilder.html#method_matchSerializedJsonBody"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchXmlBody\u0028\u0029",
            "name": "matchXmlBody",
            "summary": "Match\u0020XML\u0020request\u0020body\u0020using\u0020raw\u0020XML\u0020data.",
            "url": "classes/Pock-PockBuilder.html#method_matchXmlBody"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchSerializedXmlBody\u0028\u0029",
            "name": "matchSerializedXmlBody",
            "summary": "Match\u0020XML\u0020request\u0020body.",
            "url": "classes/Pock-PockBuilder.html#method_matchSerializedXmlBody"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AmatchCallback\u0028\u0029",
            "name": "matchCallback",
            "summary": "Match\u0020request\u0020using\u0020provided\u0020callback.\u0020Callback\u0020should\u0020receive\u0020RequestInterface\u0020and\u0020return\u0020boolean.",
            "url": "classes/Pock-PockBuilder.html#method_matchCallback"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AaddMatcher\u0028\u0029",
            "name": "addMatcher",
            "summary": "Add\u0020custom\u0020matcher\u0020to\u0020the\u0020mock.",
            "url": "classes/Pock-PockBuilder.html#method_addMatcher"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003Arepeat\u0028\u0029",
            "name": "repeat",
            "summary": "Repeat\u0020this\u0020mock\u0020provided\u0020amount\u0020of\u0020times.",
            "url": "classes/Pock-PockBuilder.html#method_repeat"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003Aalways\u0028\u0029",
            "name": "always",
            "summary": "Always\u0020execute\u0020this\u0020mock\u0020if\u0020matched.\u0020Mock\u0020with\u0020this\u0020call\u0020will\u0020not\u0020be\u0020expired\u0020ever.",
            "url": "classes/Pock-PockBuilder.html#method_always"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003Aat\u0028\u0029",
            "name": "at",
            "summary": "Match\u0020request\u0020only\u0020at\u0020Nth\u0020hit.\u0020Previous\u0020matches\u0020will\u0020not\u0020be\u0020executed.",
            "url": "classes/Pock-PockBuilder.html#method_at"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AthrowException\u0028\u0029",
            "name": "throwException",
            "summary": "Throw\u0020an\u0020exception\u0020when\u0020request\u0020is\u0020being\u0020sent.",
            "url": "classes/Pock-PockBuilder.html#method_throwException"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AthrowClientException\u0028\u0029",
            "name": "throwClientException",
            "summary": "Throw\u0020an\u0020ClientExceptionInterface\u0020instance\u0020with\u0020specified\u0020message",
            "url": "classes/Pock-PockBuilder.html#method_throwClientException"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AthrowNetworkException\u0028\u0029",
            "name": "throwNetworkException",
            "summary": "Throw\u0020an\u0020NetworkExceptionInterface\u0020instance\u0020with\u0020specified\u0020message",
            "url": "classes/Pock-PockBuilder.html#method_throwNetworkException"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AthrowRequestException\u0028\u0029",
            "name": "throwRequestException",
            "summary": "Throw\u0020an\u0020RequestExceptionInterface\u0020instance\u0020with\u0020specified\u0020message",
            "url": "classes/Pock-PockBuilder.html#method_throwRequestException"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003Areply\u0028\u0029",
            "name": "reply",
            "summary": "",
            "url": "classes/Pock-PockBuilder.html#method_reply"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AreplyWithFactory\u0028\u0029",
            "name": "replyWithFactory",
            "summary": "Construct\u0020the\u0020response\u0020during\u0020request\u0020execution\u0020using\u0020provided\u0020ReplytFactoryInterface\u0020implementation.",
            "url": "classes/Pock-PockBuilder.html#method_replyWithFactory"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AreplyWithCallback\u0028\u0029",
            "name": "replyWithCallback",
            "summary": "Construct\u0020the\u0020response\u0020during\u0020request\u0020execution\u0020using\u0020provided\u0020callback.",
            "url": "classes/Pock-PockBuilder.html#method_replyWithCallback"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AreplyWithClient\u0028\u0029",
            "name": "replyWithClient",
            "summary": "Reply\u0020to\u0020the\u0020request\u0020using\u0020provided\u0020client.\u0020Can\u0020be\u0020used\u0020to\u0020send\u0020real\u0020network\u0020request.",
            "url": "classes/Pock-PockBuilder.html#method_replyWithClient"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003Areset\u0028\u0029",
            "name": "reset",
            "summary": "Resets\u0020the\u0020builder.",
            "url": "classes/Pock-PockBuilder.html#method_reset"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AsetFallbackClient\u0028\u0029",
            "name": "setFallbackClient",
            "summary": "Sets\u0020fallback\u0020Client.\u0020It\u0020will\u0020be\u0020used\u0020if\u0020no\u0020request\u0020can\u0020be\u0020matched.",
            "url": "classes/Pock-PockBuilder.html#method_setFallbackClient"
        },                {
            "fqsen": "\\Pock\\PockBuilder\u003A\u003AgetClient\u0028\u0029",
            "name": "getClient",
            "summary": "",
            "url": "classes/Pock-PockBuilder.html#method_getClient"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder",
            "name": "PockResponseBuilder",
            "summary": "Class\u0020PockResponseBuilder",
            "url": "classes/Pock-PockResponseBuilder.html"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "PockResponseBuilder\u0020constructor.",
            "url": "classes/Pock-PockResponseBuilder.html#method___construct"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AwithStatusCode\u0028\u0029",
            "name": "withStatusCode",
            "summary": "Reply\u0020with\u0020specified\u0020status\u0020code.",
            "url": "classes/Pock-PockResponseBuilder.html#method_withStatusCode"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AwithHeader\u0028\u0029",
            "name": "withHeader",
            "summary": "Respond\u0020with\u0020specified\u0020header\u0020pattern.",
            "url": "classes/Pock-PockResponseBuilder.html#method_withHeader"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AwithAddedHeader\u0028\u0029",
            "name": "withAddedHeader",
            "summary": "Respond\u0020with\u0020specified\u0020header\u0020pattern\u0020appended\u0020to\u0020existing\u0020header.",
            "url": "classes/Pock-PockResponseBuilder.html#method_withAddedHeader"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AwithHeaders\u0028\u0029",
            "name": "withHeaders",
            "summary": "Respond\u0020with\u0020specified\u0020headers.\u0020Works\u0020exactly\u0020like\u0020calling\u0020PockResponseBuilder\u003A\u003AwithHeader\u0028\u0029\u0020would\u0020work.",
            "url": "classes/Pock-PockResponseBuilder.html#method_withHeaders"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AwithAddedHeaders\u0028\u0029",
            "name": "withAddedHeaders",
            "summary": "Respond\u0020with\u0020specified\u0020headers.\u0020Works\u0020exactly\u0020like\u0020calling\u0020PockResponseBuilder\u003A\u003AwithAddedHeader\u0028\u0029\u0020would\u0020work.",
            "url": "classes/Pock-PockResponseBuilder.html#method_withAddedHeaders"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AwithBody\u0028\u0029",
            "name": "withBody",
            "summary": "Reply\u0020with\u0020specified\u0020body.\u0020It\u0020can\u0020be\u003A\n\u0020\u002D\u0020PSR\u002D7\u0020StreamInterface\u0020\u002D\u0020it\u0020will\u0020be\u0020used\u0020without\u0020any\u0020changes.",
            "url": "classes/Pock-PockResponseBuilder.html#method_withBody"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AwithFile\u0028\u0029",
            "name": "withFile",
            "summary": "Reply\u0020with\u0020data\u0020from\u0020specified\u0020file.",
            "url": "classes/Pock-PockResponseBuilder.html#method_withFile"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AwithJson\u0028\u0029",
            "name": "withJson",
            "summary": "",
            "url": "classes/Pock-PockResponseBuilder.html#method_withJson"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AwithXml\u0028\u0029",
            "name": "withXml",
            "summary": "",
            "url": "classes/Pock-PockResponseBuilder.html#method_withXml"
        },                {
            "fqsen": "\\Pock\\PockResponseBuilder\u003A\u003AgetResponse\u0028\u0029",
            "name": "getResponse",
            "summary": "",
            "url": "classes/Pock-PockResponseBuilder.html#method_getResponse"
        },                {
            "fqsen": "\\Pock\\Promise\\HttpRejectedPromise",
            "name": "HttpRejectedPromise",
            "summary": "Class\u0020HttpRejectedPromise",
            "url": "classes/Pock-Promise-HttpRejectedPromise.html"
        },                {
            "fqsen": "\\Pock\\Promise\\HttpRejectedPromise\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "HttpRejectedPromise\u0020constructor.",
            "url": "classes/Pock-Promise-HttpRejectedPromise.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Promise\\HttpRejectedPromise\u003A\u003Athen\u0028\u0029",
            "name": "then",
            "summary": "",
            "url": "classes/Pock-Promise-HttpRejectedPromise.html#method_then"
        },                {
            "fqsen": "\\Pock\\Promise\\HttpRejectedPromise\u003A\u003AgetState\u0028\u0029",
            "name": "getState",
            "summary": "",
            "url": "classes/Pock-Promise-HttpRejectedPromise.html#method_getState"
        },                {
            "fqsen": "\\Pock\\Promise\\HttpRejectedPromise\u003A\u003Await\u0028\u0029",
            "name": "wait",
            "summary": "",
            "url": "classes/Pock-Promise-HttpRejectedPromise.html#method_wait"
        },                {
            "fqsen": "\\Pock\\Serializer\\CallbackSerializerAdapter",
            "name": "CallbackSerializerAdapter",
            "summary": "Class\u0020CallbackSerializerAdapter",
            "url": "classes/Pock-Serializer-CallbackSerializerAdapter.html"
        },                {
            "fqsen": "\\Pock\\Serializer\\CallbackSerializerAdapter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "CallbackSerializerAdapter\u0020constructor.",
            "url": "classes/Pock-Serializer-CallbackSerializerAdapter.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Serializer\\CallbackSerializerAdapter\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Serialize\u0020item",
            "url": "classes/Pock-Serializer-CallbackSerializerAdapter.html#method_serialize"
        },                {
            "fqsen": "\\Pock\\Serializer\\JmsSerializerAdapter",
            "name": "JmsSerializerAdapter",
            "summary": "Class\u0020JmsSerializerAdapter",
            "url": "classes/Pock-Serializer-JmsSerializerAdapter.html"
        },                {
            "fqsen": "\\Pock\\Serializer\\JmsSerializerAdapter\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "JmsSerializerAdapter\u0020constructor.",
            "url": "classes/Pock-Serializer-JmsSerializerAdapter.html#method___construct"
        },                {
            "fqsen": "\\Pock\\Serializer\\JmsSerializerAdapter\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Serialize\u0020item",
            "url": "classes/Pock-Serializer-JmsSerializerAdapter.html#method_serialize"
        },                {
            "fqsen": "\\Pock\\Serializer\\SerializerInterface",
            "name": "SerializerInterface",
            "summary": "Interface\u0020SerializerInterface",
            "url": "classes/Pock-Serializer-SerializerInterface.html"
        },                {
            "fqsen": "\\Pock\\Serializer\\SerializerInterface\u003A\u003Aserialize\u0028\u0029",
            "name": "serialize",
            "summary": "Serialize\u0020item",
            "url": "classes/Pock-Serializer-SerializerInterface.html#method_serialize"
        },                {
            "fqsen": "\\Pock\\Serializer\\SymfonySerializerAdapter",
            "name": "SymfonySerializerAdapter",
            "summary": "Class\u0020SymfonySerializerAdapter",
            "url": "classes/Pock-Serializer-SymfonySerializerAdapter.html"
        },                {
            "fqsen": "\\Pock\\Traits\\JsonDecoderTrait",
            "name": "JsonDecoderTrait",
            "summary": "Trait\u0020JsonDecoderTrait",
            "url": "classes/Pock-Traits-JsonDecoderTrait.html"
        },                {
            "fqsen": "\\Pock\\Traits\\JsonDecoderTrait\u003A\u003AjsonDecode\u0028\u0029",
            "name": "jsonDecode",
            "summary": "json_decode\u0020which\u0020throws\u0020exception\u0020on\u0020error.",
            "url": "classes/Pock-Traits-JsonDecoderTrait.html#method_jsonDecode"
        },                {
            "fqsen": "\\Pock\\Traits\\JsonEncoderTrait",
            "name": "JsonEncoderTrait",
            "summary": "Trait\u0020JsonEncoderTrait",
            "url": "classes/Pock-Traits-JsonEncoderTrait.html"
        },                {
            "fqsen": "\\Pock\\Traits\\JsonEncoderTrait\u003A\u003AjsonEncode\u0028\u0029",
            "name": "jsonEncode",
            "summary": "json_encode\u0020which\u0020throws\u0020exception\u0020on\u0020error.",
            "url": "classes/Pock-Traits-JsonEncoderTrait.html#method_jsonEncode"
        },                {
            "fqsen": "\\Pock\\Traits\\JsonSerializerAwareTrait",
            "name": "JsonSerializerAwareTrait",
            "summary": "Trait\u0020JsonSerializerAwareTrait",
            "url": "classes/Pock-Traits-JsonSerializerAwareTrait.html"
        },                {
            "fqsen": "\\Pock\\Traits\\SeekableStreamDataExtractor",
            "name": "SeekableStreamDataExtractor",
            "summary": "Trait\u0020SeekableStreamDataExtractor",
            "url": "classes/Pock-Traits-SeekableStreamDataExtractor.html"
        },                {
            "fqsen": "\\Pock\\Traits\\XmlSerializerAwareTrait",
            "name": "XmlSerializerAwareTrait",
            "summary": "Trait\u0020XmlSerializerAwareTrait",
            "url": "classes/Pock-Traits-XmlSerializerAwareTrait.html"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Pock",
            "name": "Pock",
            "summary": "",
            "url": "namespaces/pock.html"
        },                {
            "fqsen": "\\Pock\\Comparator",
            "name": "Comparator",
            "summary": "",
            "url": "namespaces/pock-comparator.html"
        },                {
            "fqsen": "\\Pock\\Creator",
            "name": "Creator",
            "summary": "",
            "url": "namespaces/pock-creator.html"
        },                {
            "fqsen": "\\Pock\\Enum",
            "name": "Enum",
            "summary": "",
            "url": "namespaces/pock-enum.html"
        },                {
            "fqsen": "\\Pock\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/pock-exception.html"
        },                {
            "fqsen": "\\Pock\\Factory",
            "name": "Factory",
            "summary": "",
            "url": "namespaces/pock-factory.html"
        },                {
            "fqsen": "\\Pock\\Matchers",
            "name": "Matchers",
            "summary": "",
            "url": "namespaces/pock-matchers.html"
        },                {
            "fqsen": "\\Pock\\Promise",
            "name": "Promise",
            "summary": "",
            "url": "namespaces/pock-promise.html"
        },                {
            "fqsen": "\\Pock\\Serializer",
            "name": "Serializer",
            "summary": "",
            "url": "namespaces/pock-serializer.html"
        },                {
            "fqsen": "\\Pock\\Traits",
            "name": "Traits",
            "summary": "",
            "url": "namespaces/pock-traits.html"
        }            ]
);
